Repository coinToday/FrontEnd, pull requests merged in 2025-03, with the labels that each got.

#4 feat: api 연결 완료
  src/pages/Test.tsx
Labels: test

#8 feat: 뉴스페이지 기능 구현 및 UI 개선
  .gitignore
  package.json
  src/app/App.tsx
  src/app/index.css
  src/app/index.ts
  src/entities/Button.tsx
  src/pages/MainPage.tsx
  src/pages/NewsPage.tsx
  src/widgets/sidebar/ui/sidebar.tsx
  tailwind.config.js
  yarn.lock
Labels: enhancement, feature

#9 feat: 거래 페이지 기능 추가
  src/features/CandleChart/Ui.tsx
  src/features/CandleChart/api.ts
  src/features/CandleChart/api/index.ts
  src/features/CandleChart/model.tsx
  src/features/CandleChart/model/index.js
  src/features/CandleChart/ui/index.tsx
  src/features/CoinList/api/index.ts
  src/features/CoinList/model/index.ts
  src/features/CoinList/ui/index.tsx
  src/features/OrderBook/api/index.ts
  src/features/OrderBook/model/index.ts
  src/features/OrderBook/ui/index.tsx
  src/features/Trades/api/index.ts
  src/features/Trades/model/index.ts
  src/features/Trades/ui/index.tsx
  src/features/index.ts
  src/pages/ExchangePage.tsx
  src/shared/hooks/useWebsocket.ts
  src/shared/index.ts
Labels: enhancement, feature

#11 Feature/coin list
  src/app/App.tsx
  src/app/index.ts
  src/features/CoinList/api/index.ts
  src/features/CoinList/model/index.ts
  src/features/CoinList/ui/index.tsx
  src/features/Mypage/ui/index.tsx
  src/features/index.ts
  src/layouts/layout.tsx
  src/pages/ExchangePage.tsx
  src/pages/MyPage.tsx
  src/shared/hooks/useCoin.ts
  src/shared/index.ts
  src/widgets/sidebar/ui/sidebar.tsx
Labels: feature

#12 Enhance/order book : 화면에 오더북 차트 늦게 뜨는 이슈 해결
  src/features/OrderBook/model/index.ts
  src/features/OrderBook/ui/index.tsx
  src/shared/hooks/useWebsocket.ts
Labels: enhancement

#13 Feat: 주문 설정 기능 개발 및 URL 기반 코인 선택 기능 추가
  package.json
  src/app/App.tsx
  src/app/index.ts
  src/features/News/api/index.ts
  src/features/News/model/index.ts
  src/features/News/ui/index.tsx
  src/features/OrderBook/api/index.ts
  src/features/OrderSetting/api/index.ts
  src/features/OrderSetting/model/index.ts
  src/features/OrderSetting/ui/AvgDownSection.tsx
  src/features/OrderSetting/ui/BuySection.tsx
  src/features/OrderSetting/ui/SellSection.tsx
  src/features/OrderSetting/ui/index.tsx
  src/features/Trades/api/index.ts
  src/features/Trades/model/index.ts
  src/features/Trades/ui/index.tsx
  src/features/index.ts
  src/pages/ExchangePage.tsx
  src/pages/MyPage.tsx
  src/pages/NewsPage.tsx
  src/shared/hooks/useCoin.ts
  src/shared/hooks/useWebsocket.ts
  src/widgets/sidebar/ui/sidebar.tsx
  tailwind.config.js
  yarn.lock
Labels: enhancement, feature

#14 Feature/coin: 코인 리스트에 실시간 정보 추가 및 ui 수정
  package.json
  src/app/App.tsx
  src/app/index.ts
  src/features/CandleChart/api/index.ts
  src/features/CandleChart/ui/index.tsx
  src/features/CoinList/api/fetchCoin.ts
  src/features/CoinList/api/fetchTicker.ts
  src/features/CoinList/api/index.ts
  src/features/CoinList/model/index.ts
  src/features/CoinList/model/useCoinList.ts
  src/features/CoinList/model/useCoinTicker.ts
  src/features/CoinList/ui/index.tsx
  src/features/Community/api/index.ts
  src/features/News/api/index.ts
  src/features/OrderSetting/model/index.ts
  src/features/OrderSetting/ui/BuySection.tsx
  src/main.tsx
  src/pages/JoinPage.tsx
  yarn.lock
Labels: feature
